import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated from the directory structure of the repo-root `docs/` tree.
 *
 * Hand-maintaining this list would mean every authored page needs an engineer to appear in the
 * navigation — the exact bottleneck requirements.md §1 sets out to remove.
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
