import * as aws from '@pulumi/aws';
import * as github from '@pulumi/github';
import * as pulumi from '@pulumi/pulumi';

const GITHUB_OIDC_HOST = 'token.actions.githubusercontent.com';
const STS_AUDIENCE = 'sts.amazonaws.com';

/** Key prefix a preview build is published under, one per pull request. */
const PREVIEW_PREFIX = 'pr-';

/**
 * Backstop for a pull request that is never closed.
 *
 * The workflow deletes a preview on merge or close (requirements.md R12), and that is the
 * mechanism. This is what catches the pull request left open for a quarter, and the run that was
 * cancelled between the build and the delete.
 */
const PREVIEW_RETENTION_DAYS = 30;

export interface PreviewSiteArgs {
  /** `owner/name` of the repository whose pull requests get previews. */
  readonly repositoryFullName: string;
  readonly repositoryName: pulumi.Input<string>;
  /** Where the gateway serves previews from, e.g. `http://alb-dns/previews`. */
  readonly baseUrl: pulumi.Output<string>;
  /** Taken from `PublishPipeline`, because an account holds at most one provider per URL. */
  readonly oidcProviderArn: pulumi.Output<string>;
}

/**
 * Where pull request previews live, and the credential that publishes them (requirements.md R12).
 *
 * **A bucket of its own, not a prefix on the corpus bucket.** R21 says `cms/*` branches and preview
 * builds are never ingested; a bucket the knowledge base has never been pointed at cannot be,
 * whatever anyone later does to a prefix. It also keeps the blast radius honest — this role can
 * write here and nowhere else, and the task role can read here and nowhere else.
 *
 * **No CloudFront, and no public URL.** The gateway serves `/previews/pr-<n>/` from this bucket,
 * behind whatever the load balancer already requires to reach the documentation site. A preview
 * renders unmerged changes to a corpus holding people and finance content, so it belongs inside the
 * same boundary as the published site. The cost is that preview traffic goes through ECS. See
 * ADR 0018.
 *
 * @example
 * ```ts
 * const previews = new PreviewSite('lugem-kb-dev', {
 *   repositoryFullName: 'acme/handbook',
 *   repositoryName: corpusRepository.name,
 *   baseUrl: pulumi.interpolate`${ingress.url}/previews`,
 *   oidcProviderArn: publishPipeline.oidcProviderArn,
 * });
 * ```
 */
export class PreviewSite extends pulumi.ComponentResource {
  public readonly bucketName: pulumi.Output<string>;
  public readonly bucketArn: pulumi.Output<string>;
  public readonly roleArn: pulumi.Output<string>;
  public readonly baseUrl: pulumi.Output<string>;

  constructor(name: string, args: PreviewSiteArgs, opts?: pulumi.ComponentResourceOptions) {
    super('lugem:storage:PreviewSite', name, {}, opts);

    const bucket = this.createBucket(name);
    const role = this.createRole(name, args);
    this.createPolicy(name, role, bucket.arn);
    this.publishVariables(name, args, { bucketName: bucket.bucket, roleArn: role.arn });

    this.bucketName = bucket.bucket;
    this.bucketArn = bucket.arn;
    this.roleArn = role.arn;
    this.baseUrl = args.baseUrl;

    this.registerOutputs({
      bucketName: this.bucketName,
      bucketArn: this.bucketArn,
      roleArn: this.roleArn,
      baseUrl: this.baseUrl,
    });
  }

  /**
   * Private, encrypted, and disposable.
   *
   * `forceDestroy: true` where the corpus bucket has `false`, and unversioned where the corpus is
   * versioned — both for the same reason. Retraction has to be reversible in the corpus; a preview
   * is regenerated by pushing to the pull request again, so keeping old copies of unmerged drafts
   * buys nothing and stores more unreviewed content than necessary.
   */
  private createBucket(name: string): aws.s3.Bucket {
    const bucket = new aws.s3.Bucket(
      `${name}-previews`,
      { forceDestroy: true, tags: { Component: 'previews' } },
      { parent: this },
    );

    new aws.s3.BucketServerSideEncryptionConfiguration(
      `${name}-previews-encryption`,
      {
        bucket: bucket.id,
        rules: [
          {
            applyServerSideEncryptionByDefault: { sseAlgorithm: 'AES256' },
            bucketKeyEnabled: true,
          },
        ],
      },
      { parent: this },
    );

    new aws.s3.BucketPublicAccessBlock(
      `${name}-previews-public-access-block`,
      {
        bucket: bucket.id,
        blockPublicAcls: true,
        blockPublicPolicy: true,
        ignorePublicAcls: true,
        restrictPublicBuckets: true,
      },
      { parent: this },
    );

    new aws.s3.BucketOwnershipControls(
      `${name}-previews-ownership`,
      { bucket: bucket.id, rule: { objectOwnership: 'BucketOwnerEnforced' } },
      { parent: this },
    );

    new aws.s3.BucketLifecycleConfiguration(
      `${name}-previews-lifecycle`,
      {
        bucket: bucket.id,
        rules: [
          {
            id: 'expire-abandoned-previews',
            status: 'Enabled',
            filter: { prefix: PREVIEW_PREFIX },
            expiration: { days: PREVIEW_RETENTION_DAYS },
          },
          // A cancelled `aws s3 sync` leaves parts behind, and a multipart upload nobody completes
          // is billed indefinitely while being invisible in the object listing.
          {
            id: 'abort-incomplete-uploads',
            status: 'Enabled',
            filter: {},
            abortIncompleteMultipartUpload: { daysAfterInitiation: 1 },
          },
        ],
      },
      { parent: this },
    );

    return bucket;
  }

  /**
   * The role the preview workflow assumes.
   *
   * The subject is `:pull_request` rather than the `:environment:` form the publish and gap-report
   * roles use, and that difference is forced: a deployment environment can be restricted to
   * protected branches, and a pull request head is not one. The confinement therefore lives in the
   * policy — this credential can only write under `pr-*` in one disposable bucket — and in the
   * workflow, which refuses to run for a head repository that is not this one. A fork's token
   * cannot assume this role at all: `pull_request` from a fork carries the fork's subject.
   */
  private createRole(name: string, args: PreviewSiteArgs): aws.iam.Role {
    const subject = `repo:${args.repositoryFullName}:pull_request`;

    return new aws.iam.Role(
      `${name}-preview-role`,
      {
        description: 'GitHub Actions publishes and deletes pull request documentation previews',
        assumeRolePolicy: args.oidcProviderArn.apply((arn) =>
          JSON.stringify({
            Version: '2012-10-17',
            Statement: [
              {
                Effect: 'Allow',
                Principal: { Federated: arn },
                Action: 'sts:AssumeRoleWithWebIdentity',
                Condition: {
                  StringEquals: {
                    [`${GITHUB_OIDC_HOST}:aud`]: STS_AUDIENCE,
                    [`${GITHUB_OIDC_HOST}:sub`]: subject,
                  },
                },
              },
            ],
          }),
        ),
      },
      { parent: this },
    );
  }

  /** Exactly the calls `aws s3 sync` and `aws s3 rm --recursive` make, on `pr-*` and nothing else. */
  private createPolicy(name: string, role: aws.iam.Role, bucketArn: pulumi.Output<string>): void {
    new aws.iam.RolePolicy(
      `${name}-preview-policy`,
      {
        role: role.id,
        policy: bucketArn.apply((arn) =>
          JSON.stringify({
            Version: '2012-10-17',
            Statement: [
              {
                Sid: 'ListPreviewPrefixesOnly',
                Effect: 'Allow',
                Action: ['s3:ListBucket'],
                Resource: [arn],
                Condition: { StringLike: { 's3:prefix': [`${PREVIEW_PREFIX}*`] } },
              },
              {
                Sid: 'WritePreviewPrefixesOnly',
                Effect: 'Allow',
                // `GetObject` as well as the writes: `aws s3 sync` compares before it uploads, and
                // without it every run re-uploads the whole site.
                Action: ['s3:PutObject', 's3:GetObject', 's3:DeleteObject'],
                Resource: [`${arn}/${PREVIEW_PREFIX}*`],
              },
            ],
          }),
        ),
      },
      { parent: this },
    );
  }

  /**
   * Repository variables, for the reasons `PublishPipeline.publishVariables` documents: the
   * workflow's "is this configured" gate reads them before entering any environment, and none of
   * them is a credential worth hiding from a failing run.
   */
  private publishVariables(
    name: string,
    args: PreviewSiteArgs,
    values: { readonly bucketName: pulumi.Output<string>; readonly roleArn: pulumi.Output<string> },
  ): void {
    const variables: Record<string, pulumi.Input<string>> = {
      AWS_PREVIEW_ROLE_ARN: values.roleArn,
      PREVIEW_BUCKET: values.bucketName,
      PREVIEW_BASE_URL: args.baseUrl,
    };

    for (const [variableName, value] of Object.entries(variables)) {
      const slug = variableName.toLowerCase().replace(/_/g, '-');
      new github.ActionsVariable(
        `${name}-var-${slug}`,
        { repository: args.repositoryName, variableName, value },
        { parent: this },
      );
    }
  }
}
